version: '3'
services:
  couchserver:
    image: couchdb
    ports:
      - '5984:5984'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./dbdata:/opt/couchdb/data
      - ./couchdbconfig:/opt/couchdb/etc/local.d
  
  client-1:
    image: nginx
    ports:
      - '8081:80'
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - couchserver
  
  client-2:
    image: nginx
    ports:
      - '8082:80'
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - couchserver
  
  client-3:
    image: nginx
    ports:
      - '8083:80'
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - couchserver
