version: '3'
services:
  couchserver:
    image: couchdb
    restart: always
    ports:
      - '5984:5984'
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - ./dbdata:/opt/couchdb/data
      - ./couchdbconfig:/opt/couchdb/etc/local.d
    networks:
      couchdb:
        ipv4_address: 172.19.0.2
  
  client-1:
    image: nginx
    ports:
      - '8081:80'
    volumes:
      - ./client:/usr/share/nginx/html
    depends_on:
      - couchserver
    networks:
      - couchdb

networks:
  couchdb:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
